Fixed some nuget publish issues

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -32,21 +32,27 @@ jobs:
         shell: pwsh
         run: |
           dotnet pack "${{env.Env_SolutionPath}}" `
-            --configuration "${{env.Env_Configuration}}" `
+            --verbosity normal `
             --output "${{env.Env_PublishOutputPath}}" `
+            --configuration "${{env.Env_Configuration}}" `
             --property:ContinuousIntegrationBuild=true
 
       - name: Publish to GitHub Packages
         shell: pwsh
-        env:
-          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
         run: |
           $nupkgFiles = Get-ChildItem -Path "${{env.Env_PublishOutputPath}}" -Filter "*.nupkg"
 
           foreach ($file in $nupkgFiles) {
-            Write-Host 'Publishing package "$($file.Name)"'
-            dotnet nuget push "$($file.FullName)" --source "github"
-            Write-Host 'Package "$($file.Name)" published successfully.'
+            Write-Host "Publishing package `"$($file.Name)`""
+
+            dotnet nuget push "$($file.FullName)" --source "github" --api-key "${{secrets.GITHUB_TOKEN}}"
+
+            if ($LASTEXITCODE -eq 0) {
+              Write-Host "Package `"$($file.Name)`" published successfully."
+            } else {
+              Write-Error "Failed to publish package `"$($file.Name)`""
+              exit $LASTEXITCODE
+            }
           }
 
           Write-Host "All packages have been published successfully."
